#Some of the fundamental conceprt of tensor using tensorflow.


In [ ]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
#Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#checking the number of dimenstions of a tensor
scalar.ndim   #(ndim stand for number of dimension)

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of vector
vector.ndim

1

In [ ]:
#Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another Matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                             [8., 9.]], dtype =tf.float16)  #specify the datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# The number of dimension
another_matrix.ndim

2

In [ ]:
#Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[10, 11, 12],
                       [7, 8, 9]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [ 7,  8,  9]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

#What we created so far:
Scalar: a single number
Vector: a number with direction
Matrix: a 2-dimensional array of number
Tensor: an n-dimenstonal array of numbers

In [ ]:
#Create the same tensor with tf.Variable() as above
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Let's try change one of the element in our changable tensor with the help of the .assign() operator
changable_tensor[0].assign(20)
changable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20,  7], dtype=int32)>

In [ ]:
#Let's try changing our unchangable tensor
unchangable_tensor[0].assign(12)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Creating Random Tensors
Random tensors are the tensors of some abitrary size which contain random numbers.



In [ ]:
# Create the Random(but same) tensor
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) #set seed dfor reproducibility
random_2 = random_2.normal(shape=(3,2))
random_2
# Are they equal?
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

###Shuffle the order of elements in tensor



In [ ]:
#Suffle a tensor (valuable for when you want to shuffle your data so the inherent order does,t efect order)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
#Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled, seed=7)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(10) # global level random seed
tf.random.shuffle(not_shuffled, seed=10) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

###What I understand about seed###
**Seeds**: Seeds are of two types Global seed and Operational seed.


1.  If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
2.  If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence.
3.  If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
4.  If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


##Other ways to make tensor##

In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Creating a tensor of all zeroes
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main diffrence between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [ ]:
#You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)

A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

###Getting Information from tensors
When dealing with tensors you probabily want to be aware of the following attributes:
 * Shape
 * Rank
 * Axis or Dimension
 * Size

In [ ]:
# Create a rank 4 tensors (4 dimension)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape ,rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Element along the 0 axis:", rank_4_tensor.shape[0])
print("Element along the last axis:", rank_4_tensor.shape[-1])
print("Total number of element in our tensor:", tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank) 4
Shape of tensor: (2, 3, 4, 5)
Element along the 0 axis: 2
Element along the last axis: 5
Total number of element in our tensor: tf.Tensor(120, shape=(), dtype=int32)


###Indexing tensors
Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :, :1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:, :1, :1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[7, 10],
                             [3, 5]])
rank_2_tensor, rank_2_tensor.shape, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 7, 10],
        [ 3,  5]], dtype=int32)>,
 TensorShape([2, 2]),
 2)

In [ ]:
# Get the last item of each of eanh row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 7],
        [10]],

       [[ 3],
        [ 5]]], dtype=int32)>

In [ ]:
# Alternative of tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #'-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 7],
        [10]],

       [[ 3],
        [ 5]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 7, 10],
        [ 3,  5]]], dtype=int32)>

###Manipulating tensors (tensor operations)

**Basic operations**

'+', '-', '*', '/'

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Orignal tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflolw build-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix multiplication

In machine learning, Matrix multiplication is one of the most commom tensor operations.
There are two rules our tensors (or the matrices) need to fulfill if we're going to matrix multiply them:

1. The inner dimension musty match
2. The resulting matrix has the shape of the outer matrix

In [ ]:
# Matrix multiplication for tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# Practice
a = tf.constant([[1, 2, 5],
                [7, 2, 1],
                [3, 3, 3]])
b = tf.constant([[3, 5],
                 [6, 7],
                 [1, 8]])
print(a , b)
tf.matmul(a , b)

tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32) tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operation "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Creating a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Creating other (3, 2) temsor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensors of same shape
#X @ Y


In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# Let's chane the shape of the tensor
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Try to multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Try to reshape X and then multiply
tf.reshape(X, shape=(2, 3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Can you do same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with the transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot Product**

Matrix multiplication is also refered to as the dot product.

You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Performing the dot product on X and Y (required X and Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#Peprform matrix multiplation between X and Y (transposed)
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshape)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(X), )

TypeError: Missing required positional argument

In [ ]:
# Check the values of Y, reshape Y and transpose of Y
print("Normal Y")
print(Y,"\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, shape=(2, 3)),"\n")

print("Y transposed:")
print(tf.transpose(Y))


Normal Y
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors an done of the axis doesn't line up, you will transpose(rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

##Change the datatype of the tensor

In [ ]:
#Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
c = tf.constant([17, 10])
c.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(c, dtype =tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([17., 10.], dtype=float32)>

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([17., 10.], dtype=float16)>

## Agregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
 # Getting the absolute value
 D = tf.constant([-7, -10])
 D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
#Creating a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([83, 93, 78, 57,  0, 86, 20, 39,  6,  2, 32, 16, 41,  6, 14, 49, 92,
       12, 78, 19, 34, 87,  9, 88,  2, 68, 72, 58, 17, 67, 94, 87, 76, 27,
       12, 64, 43, 55, 50, 95, 59, 83, 17, 20,  7, 76, 62, 43, 61, 45])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
#Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2401>

**Exercise:** find the variance and standard deviation of 'E'.

In [ ]:
# Find the variance of 'E'
tf.reduce_variance(E)   # Won't work

AttributeError: module 'tensorflow' has no attribute 'reduce_variance'

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=919.099609375>

In [ ]:
# To find the variance of the tensor we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=919>

In [ ]:
#Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.3166561126709>

### Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimal and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
# Find the maximun value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Finding the minimum using the positional minimum inidex
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

### Squeezing a tensor(removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-Hot encoding

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] #could be red, green, blue, purple

# One-Hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deep leaerning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep leaerning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep leaerning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep leaerning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep leaerning']],
      dtype=object)>

### Squaring log, square root

In [ ]:
# Creating a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Let's find the squareroot
tf.sqrt(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H,dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

Tensorflow interact beautifully with NumPy arrays.

In [ ]:
# Creating a tensor directly from a Numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Converting our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default types of each are slightly diffrent
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Checking the datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### finding access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Feb 17 12:51:55 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P0             26W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

**Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

##EXERCISE

* 1

In [ ]:
S = tf.constant([1])
V = tf.constant([12, 32])
M = tf.constant([[12, 18],
                 [56, 96]])
T = tf.constant([[[12, 23],
                  [34, 65]],
                 [[53, 86],
                  [64, 86]]])
print("Scalar =",S,'\n')
print("Vector =",V,'\n')
print("Matrix =",M,'\n')
print("Tensor =",T)

Scalar = tf.Tensor([1], shape=(1,), dtype=int32) 

Vector = tf.Tensor([12 32], shape=(2,), dtype=int32) 

Matrix = tf.Tensor(
[[12 18]
 [56 96]], shape=(2, 2), dtype=int32) 

Tensor = tf.Tensor(
[[[12 23]
  [34 65]]

 [[53 86]
  [64 86]]], shape=(2, 2, 2), dtype=int32)


* 2

In [ ]:
print("Scalar----\n","Shape:\n",tf.shape(S),"\nRank:\n",tf.rank(S),"\nSize\n",tf.size(S),"\n")
print("Vector----\n","Shape:\n",tf.shape(V),"\nRank:\n",tf.rank(V),"\nSize\n",tf.size(V),"\n")
print("Matrix----\n","Shape:\n",tf.shape(M),"\nRank:\n",tf.rank(M),"\nSize\n",tf.size(M),"\n")
print("Tensor----\n","Shape:\n",tf.shape(T),"\nRank:\n",tf.rank(T),"\nSize\n",tf.size(T))

Scalar----
 Shape:
 tf.Tensor([1], shape=(1,), dtype=int32) 
Rank:
 tf.Tensor(1, shape=(), dtype=int32) 
Size
 tf.Tensor(1, shape=(), dtype=int32) 

Vector----
 Shape:
 tf.Tensor([2], shape=(1,), dtype=int32) 
Rank:
 tf.Tensor(1, shape=(), dtype=int32) 
Size
 tf.Tensor(2, shape=(), dtype=int32) 

Matrix----
 Shape:
 tf.Tensor([2 2], shape=(2,), dtype=int32) 
Rank:
 tf.Tensor(2, shape=(), dtype=int32) 
Size
 tf.Tensor(4, shape=(), dtype=int32) 

Tensor----
 Shape:
 tf.Tensor([2 2 2], shape=(3,), dtype=int32) 
Rank:
 tf.Tensor(3, shape=(), dtype=int32) 
Size
 tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
import numpy as np
R1= tf.constant(np.random.uniform(0, 1),shape=[5, 300])
R2= tf.constant(np.random.uniform(0, 1),shape=[5, 300])
R1, R2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.81652534, 0.81652534, 0.81652534, ..., 0.81652534, 0.81652534,
         0.81652534],
        [0.81652534, 0.81652534, 0.81652534, ..., 0.81652534, 0.81652534,
         0.81652534],
        [0.81652534, 0.81652534, 0.81652534, ..., 0.81652534, 0.81652534,
         0.81652534],
        [0.81652534, 0.81652534, 0.81652534, ..., 0.81652534, 0.81652534,
         0.81652534],
        [0.81652534, 0.81652534, 0.81652534, ..., 0.81652534, 0.81652534,
         0.81652534]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.14228834, 0.14228834, 0.14228834, ..., 0.14228834, 0.14228834,
         0.14228834],
        [0.14228834, 0.14228834, 0.14228834, ..., 0.14228834, 0.14228834,
         0.14228834],
        [0.14228834, 0.14228834, 0.14228834, ..., 0.14228834, 0.14228834,
         0.14228834],
        [0.14228834, 0.14228834, 0.14228834, ..., 0.14228834, 0.14228834,
         0.14228834],
        [0.14228

* 3

In [ ]:
tf.matmul(R1,tf.transpose(R2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[34.854618, 34.854618, 34.854618, 34.854618, 34.854618],
       [34.854618, 34.854618, 34.854618, 34.854618, 34.854618],
       [34.854618, 34.854618, 34.854618, 34.854618, 34.854618],
       [34.854618, 34.854618, 34.854618, 34.854618, 34.854618],
       [34.854618, 34.854618, 34.854618, 34.854618, 34.854618]],
      dtype=float32)>

* 4

In [ ]:
R1* R2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.11618204, 0.11618204, 0.11618204, ..., 0.11618204, 0.11618204,
        0.11618204],
       [0.11618204, 0.11618204, 0.11618204, ..., 0.11618204, 0.11618204,
        0.11618204],
       [0.11618204, 0.11618204, 0.11618204, ..., 0.11618204, 0.11618204,
        0.11618204],
       [0.11618204, 0.11618204, 0.11618204, ..., 0.11618204, 0.11618204,
        0.11618204],
       [0.11618204, 0.11618204, 0.11618204, ..., 0.11618204, 0.11618204,
        0.11618204]], dtype=float32)>

* 5

In [ ]:
R3 = tf.constant(np.random.uniform(0,1), shape= [224, 224, 3])
R3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124],
        ...,
        [0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124]],

       [[0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124],
        ...,
        [0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124]],

       [[0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124],
        ...,
        [0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124],
        [0.01072124, 0.01072124, 0.01072124]],

       ...,

       [[0.01072124, 0.01072124, 0.01072124],
        [0.01

* 6

In [ ]:
tf.reduce_min(R3, axis=1)
tf.reduce_min(R3, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
       [0.01072124, 0.01072124, 0.01072124],
     

* 7

In [ ]:
R4 = tf.random.normal(shape=[1, 224, 224, 3])
R4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[-1.3439283 , -0.4599228 ,  0.683877  ],
         [-0.0786004 ,  0.48405337, -0.2809769 ],
         [ 0.97056085, -0.33109573, -0.2749624 ],
         ...,
         [-0.95627075, -0.73960096, -0.5376725 ],
         [-1.0573492 ,  1.2474251 , -1.8117028 ],
         [-2.4591591 , -0.7624955 , -0.27922407]],

        [[ 0.83559763,  0.4883239 , -0.32644302],
         [ 0.76833147,  1.4723433 , -1.2558787 ],
         [-1.4637932 ,  0.16058707, -1.456632  ],
         ...,
         [ 1.8569008 ,  0.2182672 ,  0.5554358 ],
         [ 0.27321455, -0.72538817, -1.9232535 ],
         [ 1.639396  , -1.0947585 , -1.3753735 ]],

        [[-0.4943404 , -1.1795999 , -0.11746896],
         [-0.26266363, -0.6127106 , -1.8998497 ],
         [ 1.2748008 ,  1.3314103 , -0.6186011 ],
         ...,
         [ 0.29339603,  0.02488334, -0.45498395],
         [ 0.29865885,  1.3306736 , -0.88237   ],
         [-0.79015124, -1.3738977 ,  0.2706268

In [ ]:
R5= tf.squeeze(R4)
R5, tf.shape(R5)

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[-1.3439283 , -0.4599228 ,  0.683877  ],
         [-0.0786004 ,  0.48405337, -0.2809769 ],
         [ 0.97056085, -0.33109573, -0.2749624 ],
         ...,
         [-0.95627075, -0.73960096, -0.5376725 ],
         [-1.0573492 ,  1.2474251 , -1.8117028 ],
         [-2.4591591 , -0.7624955 , -0.27922407]],
 
        [[ 0.83559763,  0.4883239 , -0.32644302],
         [ 0.76833147,  1.4723433 , -1.2558787 ],
         [-1.4637932 ,  0.16058707, -1.456632  ],
         ...,
         [ 1.8569008 ,  0.2182672 ,  0.5554358 ],
         [ 0.27321455, -0.72538817, -1.9232535 ],
         [ 1.639396  , -1.0947585 , -1.3753735 ]],
 
        [[-0.4943404 , -1.1795999 , -0.11746896],
         [-0.26266363, -0.6127106 , -1.8998497 ],
         [ 1.2748008 ,  1.3314103 , -0.6186011 ],
         ...,
         [ 0.29339603,  0.02488334, -0.45498395],
         [ 0.29865885,  1.3306736 , -0.88237   ],
         [-0.79015124, -1.3738977 ,  0.2706268

* 8

In [ ]:
R6 = tf.constant([23, 7654, 536, 645, 45, 75, 867, 876, 8079, 698])
R6[tf.argmax(R6)]

<tf.Tensor: shape=(), dtype=int32, numpy=8079>

* 9

In [ ]:
tf.one_hot(R6, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

* 10